'''
以下为登陆数据
初始化使用
'''
from selenium.webdriver.common.by import By
'''
这是点击我的id
log_me是接受的变量值
'''
log_wo=By.ID,"com.yunmall.lc:id/tab_me"
'''
这是点击已有账户登陆，去登陆的id
log_you是接受的变量值
'''
log_you=By.ID,"com.yunmall.lc:id/textView1"
'''
这是输入用户名的id,
log_shu是接受的变量值
'''
log_shu=By.ID,"com.yunmall.lc:id/logon_account_textview"
'''
这是输入密码的id,
log_mi是接受的变量值
'''
log_mi=By.ID,"com.yunmall.lc:id/logon_password_textview"
'''
这是点击登陆的id,
log_deng是接受的变量值
'''
log_deng=By.ID,"com.yunmall.lc:id/logon_button"
'''
这是昵称的id,,
log_niceng是接受的变量值
'''
log_niceng=By.ID,"com.yunmall.lc:id/tv_user_nikename"
'''
这是设置的id,,
log_she是接受的变量值
'''
log_she=By.ID,"com.yunmall.lc:id/ymtitlebar_left_btn_image"
'''
这是修改密码的id,,
log_xiumi是接受的变量值
'''
log_xiumi=By.ID,"com.yunmall.lc:id/setting_modify_pwd"

'''
这是的短信提醒的id,,
log_duan是接受的变量值
'''
log_duan=By.ID,"com.yunmall.lc:id/setting_sms_notify"
'''
这是点击退出的id
log_tui是接受的变量值
'''
log_tui=By.ID,"com.yunmall.lc:id/setting_logout"
'''
这是确认退出的id
log_tui_ok是接受的变量值
'''
log_tui_ok=By.ID,"com.yunmall.lc:id/ymdialog_right_button"